
title: Ahmet Amasyalı
email: ahmetamasyali@hotmail.com
description: Ahmet Amasyali's Personal Blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://ahmetamasyali.github.io" # the base hostname & protocol for your site
github_username:  ahmet amasyali
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
